// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDe77JaF0kwBhuF_ocS7hFbN5jvVue34s',
    appId: '1:694440650974:web:a240f91c1035e68d503a4f',
    messagingSenderId: '694440650974',
    projectId: 'chatbox-90946',
    authDomain: 'chatbox-90946.firebaseapp.com',
    storageBucket: 'chatbox-90946.firebasestorage.app',
    measurementId: 'G-PNQPYE0GCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3_dkLXNz5jkI6cvnsk2DI6KA15A4zpMw',
    appId: '1:694440650974:android:f859bb1d45eb4014503a4f',
    messagingSenderId: '694440650974',
    projectId: 'chatbox-90946',
    storageBucket: 'chatbox-90946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7T8IRY6ikbJem3ialT6u8mTtFHDuU9-A',
    appId: '1:694440650974:ios:901ba3d1cd02a2c2503a4f',
    messagingSenderId: '694440650974',
    projectId: 'chatbox-90946',
    storageBucket: 'chatbox-90946.firebasestorage.app',
    iosBundleId: 'com.example.sbchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7T8IRY6ikbJem3ialT6u8mTtFHDuU9-A',
    appId: '1:694440650974:ios:901ba3d1cd02a2c2503a4f',
    messagingSenderId: '694440650974',
    projectId: 'chatbox-90946',
    storageBucket: 'chatbox-90946.firebasestorage.app',
    iosBundleId: 'com.example.sbchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDe77JaF0kwBhuF_ocS7hFbN5jvVue34s',
    appId: '1:694440650974:web:876149401da0e2ee503a4f',
    messagingSenderId: '694440650974',
    projectId: 'chatbox-90946',
    authDomain: 'chatbox-90946.firebaseapp.com',
    storageBucket: 'chatbox-90946.firebasestorage.app',
    measurementId: 'G-8RRPG1SETM',
  );
}
